### ISSUE TITLE
pop_up True throw exception

### ISSUE THREAD

**Issue by wiryonolau** [davidhozic/Tkinter-Async-Execute#9]
Hi I'm not sure what is the cause of error, it happen in v1.3.0 , v1.2.0 ok

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/.../view/widget.py", line 104, in _on_click
    tkae.async_execute(
  File "/.../lib/python3.11/site-packages/tk_async_execute/utils.py", line 181, in async_execute
    window = ExecutingAsyncWindow(coro, visible, pop_up, callback, show_exceptions, message, show_stdout, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../lib/python3.11/site-packages/tk_async_execute/widget.py", line 137, in __init__
    self.grab_set()
  File "/usr/lib/python3.11/tkinter/__init__.py", line 963, in grab_set
    self.tk.call('grab', 'set', self._w)
_tkinter.TclError: grab failed: window not viewable
sys:1: RuntimeWarning: coroutine '....' was never awaited
```
could you add wait_visibility() in the pop_up ?

```python
if pop_up:
    self.wait_visibility()
    self.grab_set()
```

All the windows is already shown but it still say window not viewable.

**Comment by davidhozic** [comment]
Fixed :), https://pypi.org/project/tkinter-async-execute/1.3.1/
